// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjydxbqbmpjkosvykrpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqeWR4YnFibXBqa29zdnlrcnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTYxODQyNjQsImV4cCI6MjAzMTc2MDI2NH0.pHszS6AQIS_IK7HqwLJz8I1PY_y4xrRYdyyDW1VNDaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);